### ISSUE TITLE
rg / grep option

### ISSUE THREAD

**Issue by lxhillwind** [lacygoill/vim-fuzzy#1]
https://github.com/lacygoill/vim-fuzzy/blob/fa6a7199ce8ff85b3c482f801c4a991f76d61a16/autoload/fuzzy.vim#L409

Seems that rg `-n` option is missing. If rg option is not set in other place (like in `$RIPGREP_CONFIG_PATH`), then `:FzGrep` will report error; add `-n` option fixes it.

(Things not relative to this issue: would you mind to create a license file for this repository? I would like to include this repository in my dotfiles, with my own patch which is not suitable to be push to upstream (this repo), like using busybox-w32 as shell)

**Comment by lacygoill** [comment]
> Seems that rg -n option is missing.

You're right.  I think this should be fixed by [this commit](https://github.com/lacygoill/vim-fuzzy/commit/2296b2f752c11855f6c71691b25b556a31bb42aa).

   > would you mind to create a license file for this repository?

OK, [this other commit](https://github.com/lacygoill/vim-fuzzy/commit/1a4dc578ec0b60beeb13ea62122077f74cd5603e) should have added a license.
