### ISSUE TITLE
`<Space>fc` (FzCommands) display some commands with completion incorrectly

### ISSUE THREAD

**Issue by lxhillwind** [lacygoill/vim-fuzzy#3]
This can be triggerd when a command is defined with `-complete=custom[list],XXX` (XXX is a long function name).

MRE:

```vim
vim9script
set pp=~/vimfiles  # modify if necessary
syntax on  # without this, it is not initialized correctly
packadd vim-fuzzy-origin  # modify if necessary

command! -nargs=* -complete=custom,LongFuncName MRE echo
def LongFuncName(..._: list<any>): string
    return ''
enddef
```

expect:

search "MRE", something like this shows:

    MRE                 echo        mre.vim:6

actually:

    MREFuncName         echo        mre.vim:6

why:

`:verbose command MRE` gives the following result (command-complete info may exceeds 43 columns):

```console
    Name              Args Address Complete    Definition
    MRE               *            custom,LongFuncName echo
        Last set from /tmp/mre.vim line 6
```

So maybe the regex here <https://github.com/lacygoill/vim-fuzzy/blob/51a3b3109d9822493addacfcb885f1875148fda1/autoload/fuzzy.vim#L458>
should be modified to `^\S*\zs.*\%43c\S*` (with "\S*" after it)?

**Comment by lacygoill** [comment]
Sorry for the late response; I was not notified of the issue because I didn't watch the repo.

I included the suggested fix in [this commit](https://github.com/lacygoill/vim-fuzzy/commit/b38a59a5143350b1257dd2f44907f3ea71bb6e35).

**Comment by lacygoill** [comment]
And thank you for the report.  I think the fix is correct.

**Comment by lxhillwind** [comment]
Thanks!
